In [65]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random
from wordcloud import WordCloud


##Preprocessing of the data

###Exploring the data

In [66]:
pd.read_csv("/content/bankdataset.csv")

              Date         Domain   Location    Value  Transaction_count
0       01-01-2022      RESTRAUNT       Bhuj   365554               1932
1       01-01-2022    INVESTMENTS   Ludhiana   847444               1721
2       01-01-2022         RETAIL        Goa   786941               1573
3       01-01-2022  INTERNATIONAL    Mathura   368610               2049
4       01-01-2022      RESTRAUNT    Madurai   615681               1519
...            ...            ...        ...      ...                ...
238343  28-03-2022        MEDICAL     Trichy  1164302               1771
238344  28-03-2022         PUBLIC    Kolkata   881635                805
238345  28-03-2022      EDUCATION  Hyderabad   547066               2457
238346  28-03-2022      RESTRAUNT       Pune   748998               1487
238347  28-03-2022      RESTRAUNT     Kanpur  1121272                 16

[238348 rows x 5 columns]

In [67]:
data  = pd.read_csv("/content/bankdataset.csv")

In [68]:
data.shape

(238348, 5)

In [69]:
data.tail()

              Date     Domain   Location    Value  Transaction_count
238343  28-03-2022    MEDICAL     Trichy  1164302               1771
238344  28-03-2022     PUBLIC    Kolkata   881635                805
238345  28-03-2022  EDUCATION  Hyderabad   547066               2457
238346  28-03-2022  RESTRAUNT       Pune   748998               1487
238347  28-03-2022  RESTRAUNT     Kanpur  1121272                 16

In [70]:
data.head()

         Date         Domain  Location   Value  Transaction_count
0  01-01-2022      RESTRAUNT      Bhuj  365554               1932
1  01-01-2022    INVESTMENTS  Ludhiana  847444               1721
2  01-01-2022         RETAIL       Goa  786941               1573
3  01-01-2022  INTERNATIONAL   Mathura  368610               2049
4  01-01-2022      RESTRAUNT   Madurai  615681               1519

In [71]:
data.Domain.unique()

array(['RESTRAUNT', 'INVESTMENTS', 'RETAIL', 'INTERNATIONAL', 'PUBLIC',
       'MEDICAL', 'EDUCATION'], dtype=object)

In [72]:
data.Domain.nunique()

7

In [73]:
data[data['Domain'] == "PUBLIC"]

              Date  Domain  Location    Value  Transaction_count
7       01-01-2022  PUBLIC    Trichy  1030297                606
10      01-01-2022  PUBLIC   Lucknow   912902               1035
12      01-01-2022  PUBLIC  Amritsar   849803               2013
16      01-01-2022  PUBLIC    Kannur   933938               1362
37      01-01-2022  PUBLIC     Daman   765631               1876
...            ...     ...       ...      ...                ...
238314  28-03-2022  PUBLIC     Bhind   438867               1167
238319  28-03-2022  PUBLIC    Kochin  1064129               2233
238326  28-03-2022  PUBLIC      Doda   918262               2389
238335  28-03-2022  PUBLIC     Bhind   408246               1009
238344  28-03-2022  PUBLIC   Kolkata   881635                805

[34090 rows x 5 columns]

In [74]:
data[data['Domain'] == "RETAIL"]

              Date  Domain  Location    Value  Transaction_count
2       01-01-2022  RETAIL       Goa   786941               1573
14      01-01-2022  RETAIL      Doda  1003497               1654
17      01-01-2022  RETAIL   Lunglei   521003               2304
21      01-01-2022  RETAIL  Amritsar   907177               2042
27      01-01-2022  RETAIL     Bhind   555766               2035
...            ...     ...       ...      ...                ...
238300  28-03-2022  RETAIL      Durg   484061                498
238306  28-03-2022  RETAIL     Buxar   618461                630
238321  28-03-2022  RETAIL  Amritsar   951188               1126
238323  28-03-2022  RETAIL      Kota   693568               1902
238342  28-03-2022  RETAIL       Goa   378315               2365

[33825 rows x 5 columns]

In [75]:
data.shape

(238348, 5)

our data has 2 million plus rows and 26 columns.

Let us go and understand what are all there in these rows and columns

In [76]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 238348 entries, 0 to 238347
Data columns (total 5 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Date               238348 non-null  object
 1   Domain             238348 non-null  object
 2   Location           238348 non-null  object
 3   Value              238348 non-null  int64
 4   Transaction_count  238348 non-null  int64
dtypes: int64(2), object(3)
memory usage: 9.1+ MB

In [77]:

data.describe()

              Value  Transaction_count
count  2.383480e+05      238348.000000
mean   7.492597e+05        1471.917876
std    2.608303e+05         620.242373
min    2.984290e+05          16.000000
25%    5.231560e+05         936.000000
50%    7.494105e+05        1471.000000
75%    9.742608e+05        2008.000000
max    1.202271e+06        2548.000000

As the dataset that we have taken may be having duplicate values, try to understand this : when we are filling out the form we may fill one or more times and ending up increase the amount of responses.  So it is better to remove all the duplicates before getting in to the analysis part.

In [82]:
data.drop_duplicates(['Location'],keep = 'first', inplace = True)

In [78]:
data.shape

(238348, 5)

# Dealing with the missing values.

In [79]:
data.isnull()

         Date  Domain  Location  Value  Transaction_count
0       False   False     False  False              False
1       False   False     False  False              False
2       False   False     False  False              False
3       False   False     False  False              False
4       False   False     False  False              False
...       ...     ...       ...    ...                ...
238343  False   False     False  False              False
238344  False   False     False  False              False
238345  False   False     False  False              False
238346  False   False     False  False              False
238347  False   False     False  False              False

[238348 rows x 5 columns]

In [80]:
data.isnull().sum()

Date                 0
Domain               0
Location             0
Value                0
Transaction_count    0
dtype: int64

In [83]:
data['Transaction_count']

0      1932
1      1721
2      1573
3      2049
4      1519
5      1813
6      2098
7       606
8      1463
9      1463
10     1035
11     1093
12     2013
14     1654
15     1686
16     1362
17     2304
18     1202
20     1492
23     1892
27     2035
28     1652
29      480
32     2082
34     1883
39     1691
43     1355
45      430
48     1704
51     1536
54     1150
55     2080
58     1778
59     2015
61      533
62     2235
65     1350
67     1152
68     1460
71     1634
76     2470
93     2521
109     551
168    2133
226    1239
235    1144
Name: Transaction_count, dtype: int64

In [84]:
#checking out the unique values

data['Domain'].unique()

array(['RESTRAUNT', 'INVESTMENTS', 'RETAIL', 'INTERNATIONAL', 'PUBLIC',
       'MEDICAL', 'EDUCATION'], dtype=object)

In [85]:
data['Domain'].nunique()

7

In [86]:
print(data['Domain'].unique()[0])

RESTRAUNT

In [87]:
type(data['Value'].unique()[0])

numpy.int64

In [88]:
#Removing [' '] from the each value

data['Domain'] = data['Domain'].apply(lambda x:x[2:-2])
print(data['Domain'].unique())

['STRAU' 'VESTMEN' 'TA' 'TERNATION' 'BL' 'DIC' 'UCATI']

In [92]:
data['Transaction_count'].unique()

array([1932, 1721, 1573, 2049, 1519, 1813, 2098,  606, 1463, 1035, 1093,
       2013, 1654, 1686, 1362, 2304, 1202, 1492, 1892, 2035, 1652,  480,
       2082, 1883, 1691, 1355,  430, 1704, 1536, 1150, 2080, 1778, 2015,
        533, 2235, 1350, 1152, 1460, 1634, 2470, 2521,  551, 2133, 1239,
       1144])

In [94]:
len(data['Value'].unique())

46

In [95]:
data[data['Location'] ==  "Bhuj"]

         Date Domain Location   Value  Transaction_count
0  01-01-2022  STRAU     Bhuj  365554               1932

In [96]:
data['Transaction_count'].head()

0    1932
1    1721
2    1573
3    2049
4    1519
Name: Transaction_count, dtype: int64

In [97]:
#checking out the unique values

data['Value'].unique()

array([ 365554,  847444,  786941,  368610,  615681, 1191092,  968883,
       1030297,  688655, 1174302,  912902,  436534,  849803, 1003497,
        616724,  933938,  521003,  849779,  762330,  778068,  555766,
        574197,  327304, 1155932,  685980,  435491,  369580, 1138214,
        893467,  988853,  388211, 1190426,  316227, 1130802,  958103,
        900899,  418787,  851047,  299768,  546797,  552250,  561069,
        362553,  474238,  643567,  961985])

In [98]:
data['Value'].nunique()

46

In [99]:
data['Date'] = data['Date'].fillna("No Date")

In [100]:
data['Date'].isnull().sum()

np.int64(0)

In [104]:
Value = []
data['Value'].apply(lambda x:Value.extend(x.split(",")))
Date = pd.Series(Values)
print("Total No. of Value =  ", Value.nunique())

AttributeError: 'int' object has no attribute 'split'

In [109]:
data['Location']

0           Bhuj
1       Ludhiana
2            Goa
3        Mathura
4        Madurai
5          Daman
6          Buxar
7         Trichy
8          Kullu
9      Hyderabad
10       Lucknow
11       Bikaner
12      Amritsar
14          Doda
15        Jaipur
16        Kannur
17       Lunglei
18        Bombay
20          Pune
23         Ajmer
27         Bhind
28         Akola
29        Kanpur
32        Bhopal
34       Vellore
39         Surat
43        Ranchi
45      Banglore
48      Tirumala
51        Bokaro
54        Ambala
55           Ara
58        Konark
59         Betul
61       Patiala
62     Ahmedabad
65         Bidar
67        Indore
68      Srinagar
71       Kolkata
76          Durg
93        Kochin
109         Kota
168        Delhi
226          Mon
235     Varanasi
Name: Location, dtype: object

In [110]:
data['Location'].unique()

array(['Bhuj', 'Ludhiana', 'Goa', 'Mathura', 'Madurai', 'Daman', 'Buxar',
       'Trichy', 'Kullu', 'Hyderabad', 'Lucknow', 'Bikaner', 'Amritsar',
       'Doda', 'Jaipur', 'Kannur', 'Lunglei', 'Bombay', 'Pune', 'Ajmer',
       'Bhind', 'Akola', 'Kanpur', 'Bhopal', 'Vellore', 'Surat', 'Ranchi',
       'Banglore', 'Tirumala', 'Bokaro', 'Ambala', 'Ara', 'Konark',
       'Betul', 'Patiala', 'Ahmedabad', 'Bidar', 'Indore', 'Srinagar',
       'Kolkata', 'Durg', 'Kochin', 'Kota', 'Delhi', 'Mon', 'Varanasi'],
      dtype=object)

In [107]:
data['Location'].nunique()

46

15. Timings - This feature is also having the missing values, but we are having large number of unique classes. and it is not even structured properly. better we avoid this feature

16. average_cost_of_two - this is an excellent feature, we are having value "0", this should be an outlier.

In [108]:
data['Transaction_count'].nunique()

45